package libenv

type Env struct {
	HOSTTYPE                                 string
	CLUSTER                                  string
	DEBUG                                    bool
	STAGE                                    string
	EXPOSEPORT                               string
	APPLABEL                                 string
	JWT_SECRET                               string
	MSQL_USERNAME                            string
	MSQL_PASSWORD                            string
	MSQL_SERVICENAME                         string
	MSQL_PORT                                string
	MSQL_Client_DBNAME                       string
	MSQL_contractmaster_DBNAME               string
	MSQL_edis_DBNAME                         string
	MSQL_facetrade_DBNAME                    string
	MSQL_tracker_DBNAME                      string
	MSQL_IFSC_DBNAME                         string
	MSQL_papertrade_DBNAME                   string
	MSQL_jwtauth_DBNAME                      string
	MSQL_smartsearch_DBNAME                  string
	MSQL_advisory_DBNAME                     string
	MSQL_auth_DBNAME                         string
	MSQL_gowsproxy_DBNAME                    string
	MSQL_stocksearch_DBNAME                  string
	MSQL_techexcel_DBNAME                    string
	MSQL_ACCORD_DBNAME                       string
	MSQL_watchlist_DBNAME                    string
	MSQL_switchaccount_DBNAME                string
	MSQL_SettingService_DBNAME               string
	MSQL_MUTUALFUND_DBNAME                   string
	MSQL_ADMIN_MASTER_DBNAME                 string
	MSQL_interactivebroker_DBNAME            string
	MSQL_NOTIS_DBNAME                        string
	MSQL_IPO_DBNAME                          string
	MSQL_STOCKAL_DBNAME                      string
	RAZORPAY_KEY_TPV                         string
	RAZORPAY_SECRET_TPV                      string
	RAZORPAY_NAME_TPV                        string
	RAZORPAY_KEY_NON_TPV                     string
	RAZORPAY_SECRET_NON_TPV                  string
	RAZORPAY_NAME_NON_TPV                    string
	MSQL_payment_DBNAME                      string
	FIREBASE_SERVICEKEY_PATH                 string
	FIREBASE_WEB_PUBLICK_EY                  string
	FIREBASE_WEB_PRIVATE_KEY                 string
	AWS_S3_REGION                            string
	AWS_S3_BUCKET                            string
	AWS_ACCESS_KEY_ID                        string
	AWS_SECRET_ACCESS_KEY                    string
	VOLUMNE_PATH                             string
	LOG_PATH                                 string
	MY_NODE_NAME                             string
	MY_POD_NAME                              string
	MY_POD_NAMESPACE                         string
	MY_POD_IP                                string
	MY_POD_SERVICE_ACCOUNT                   string
	SERVER_TYPE                              string
	REDIS_SERVICE                            string
	REDIS_PORT                               string
	REDIS_PASSWORD                           string
	PATH_REPLACE                             string
	SMTPUSERNAME                             string
	SMTPApiKey                               string
	DGIOAUTHKEY                              string
	FROM                                     string
	DI_DB_PAPERTRADE                         string
	DI_DB_JWTAUTH                            string
	DI_DB_FACETRADE                          string
	DI_DB_TRACKER                            string
	DI_DB_ADMINMASTER                        string
	DI_DB_EDIS                               string
	DI_DB_CONTRACTS                          string
	DI_DB_CLINTMASTER                        string
	DI_DB_ADVISORY                           string
	DI_DB_ZEROLOGS                           string
	DI_DB_ACCORD                             string
	DI_DB_WATCHLIST                          string
	DI_DB_SWITCHACCOUNT                      string
	DI_DB_SettingService                     string
	DI_DB_INTERACIVEBROKER                   string
	DI_DB_IPO                                string
	DI_DB_PAYMENT                            string
	DI_DB_MUTUALFUND                         string
	DI_DB_NOTIS                              string
	DI_DB_STOCKAL                            string
	DPId                                     string
	ROUTE_SERVER                             string
	HYPERSYNC_HOLDING_URL                    string
	JWT_ACCESS_TOKEN_TIME_TO_EXPIRE_IN_DAY   int
	JWT_REFRESH_TOKEN_TIME_TO_EXPIRE_IN_DAYS int
	PROMETHEUS_HOOK                          bool
	PROMETHEUS_COUNTER                       bool
	PROMETHEUS_GAUGE                         bool
	PROMETHEUS_HISTOGRAM                     bool
	PROMETHEUS_SUMMARY                       bool
	PROMETHEUS_PORT                          int
	FILE_USERDATA_PATH                       string
	JMETER_PATH                              string
	JMETER_GITHUB_PATH                       string
	REPORT_PATH                              string
	KUB_WEB_ADDRESS                          string
	FILE_POA                                 string
	SECRET                                   string
	JWTKEY                                   string
	JWTISSUER                                string
	JWTAUDIENCE                              string
	JWT_GITHUB_JWT                           string
	GOOGLE_REDIRECT_URL                      string
	GOOGLE_SECRET_PATH                       string
	GOOGLE_LOGIN_PAGE                        string
	GOOGLE_REDIRECT_PAGE                     string
	GOOGLE_MOBILE_PAGE                       string
	GOOGLE_CLIENTID                          string
	GOOGLE_CLIENTSECRET                      string
	GOOGLE_MAIN_PAGE                         string
	GOOGLE_MPIN_PAGE                         string
	HS_PUBLIC_KEY                            string
	HS_AUTH_KEY                              string
	SLACKURL_ACCORDCRONJOB                   string
	NUUU_MAIN_WEBURL                         string
	GOOGLE_SETMPIN_PAGE                      string
	GOOGLE_REGISTER_PAGE                     string
	GOOGLE_FORGOT_PAGE                       string
	GOOGLE_UNBLOCK_PAGE                      string
	GOOGLE_SETPASSWORD_PAGE                  string
	STOCKPAGE_ACCORD_SEARCH_URL              string
	ACCORD_SERVICE_URL                       string
	GITHUB_STOCKPAGES_URL                    string
	GITHUB_STOCKPAGES_DIR                    string
	GITHUB_USERNAME                          string
	GITHUB_PASSWORD                          string
	GITHUB_STOCKPAGES_CLEAN_CACHEFILE_URL    string
	SLACK_STOCKPAGES_URL                     string
	SLACK_HELM_UPDATE_URL                    string
	SMS_EMAIL_SERVICE_URL                    string
	GO_JWT_SERVICE_URL                       string
	ACCORD_KEY                               string
	SETTLEMENT_FILE_PATH                     string
	BASEPATH                                 string
	EQPATH                                   string
	FOPATH                                   string
	CDPATH                                   string
	RAWPATH                                  string
	NSETimeFormat                            string
	NSEEQ_Start_Time                         string
	NSEEQ_End_Time                           string
	NSEFO_Start_Time                         string
	NSEFO_End_Time                           string
	NSECD_Start_Time                         string
	NSECD_End_Time                           string
	NSEEQ_Min_Time                           string
	NSEEQ_MAX_Time                           string
	NSEFO_Min_Time                           string
	NSEFO_MAX_Time                           string
	NSECD_Min_Time                           string
	NSECD_MAX_Time                           string
	SlackURL                                 string
	INDEX_MASTER_URL                         string
	TYPESENSE_KEY                            string
	TYPESENSE_VALUE                          string
	TYPESENSE_BASE_URL                       string
	CONTRACTMASTER_TYPESENSE_COLLECTION      string
	CONTRACTMASTER_TYPESENSE_QUERY_BY        string
	CONTRACTMASTER_TYPESENSE_GROUP_BY        string
	TYPESENSE_GROUP_LIMIT                    string
	TYPESENSE_EXHAUSTIVE_SEARCH              string
	CONTRACTMASTER_TYPESENSE_PERPAGE         string
	CONTRACTMASTER_TYPESENSE_SORT_BY         string
	MUTUALFUND_TYPESENSE_COLLECTION          string
	MUTUALFUND_TYPESENSE_QUERY_BY            string
	MUTUALFUND_TYPESENSE_QUERY_BY_SCHCODE    string
	MUTUALFUND_TYPESENSE_FACET_QUERY_BY      string
	MUTUALFUND_TYPESENSE_SORT_BY             string
	ACCORD_TYPESENSE_COLLECTION              string
	ACCORD_TYPESENSE_QUERY_BY                string
	ACCORD_TYPESENSE_SORT_BY                 string
	ACCORD_TYPESENSE_PERPAGE                 string
	NAMESPACE_WEBHOOK                        string
	IS_RAW_FILE_WRITING_ENABLE               string
	BOID                                     string
	CMID                                     string
	TMID                                     string
	NumOfDays                                string
	ExID                                     string
	ReturnURL                                string
	ReqIdentifier                            string
	ReqType                                  string
	Version                                  string
	TB_SECRET_KEY                            string
	TB_SECRETIV_KEY                          string
	TB_PARTNERID_KEY                         string
	TB_MODULE_NAME                           string
	FILE_TEMPLATE_PATH                       string
	WA_BASE_URL                              string
	WA_EKYC_MESSAGE_URL                      string
	WA_GET_TOKEN_URL                         string
	WA_EKYCID                                string
	WA_WHATSAPP_URL                          string
	WA_WHATSAPP_TOKEN                        string
	LEX_BotID                                string
	LEX_BotAlias                             string
	LEX_BotAliasID                           string
	LEX_LocalID                              string
	GOOGLE_TOTP_PAGE                         string
	CASHFREE_CLIENT_ID                       string
	CASHFREE_CLIENT_SECRET                   string
	IPO_MEMBER                               string
	IPO_USER_ID                              string
	IPO_MEMBER_PASSWORD                      string
	WA_FINVUID                               string
	WA_FINVU_MESSAGE_URL                     string
	WA_FINVU_TOKEN                           string
	MAX_OTP_ATTEMPT                          int
	MAX_PASSWORD_ATTEMPT                     int
	MAX_MPIN_ATTEMPT                         int
	MAX_WATCHLIST_Limit                      int
	GOOGLE_FORGOTMPIN_PAGE                   string
	GW_URL                                   string
	GW_KEY                                   string
	ANDROIDMINVERSION                        string
	ANDROIDMAXVERSION                        string
	IOSMINVERSION                            string
	IOSMAXVERSION                            string
	IS_FINVU                                 bool
	BROKERID                                 string
	SLACKURL_EDIS                            string
	EDISDONE_PAGE                            string
	BLOCK_USER_PAGE                          string
	NUUU_JWT_URL                             string
	LEX_LAMBDA_PROD_SERVER                   string
	IPO_LOGIN_TICKER_SECS                    int
	IPO_HEARTBEAT_TICKER_MIN                 int
	IPO_API_URL                              string
	PLAN_SUBSCRIPTION_ID                     string
	SIDECAR_IP                               string
	EXPOSEPORT_SIDECAR                       string
	EXPOSEPORT_SENDER_PORT                   string
	TOPIC_SUB                                string
	TOPIC_PUB                                string
	MSQL_Whatsapp_DBNAME                     string
	IPO_LOGIN_RETRIES_MAX_COUNT              int
	IPO_DB_CHANNEL_SIZE                      int
	EDISFAILURE_PAGE                         string
	MUTF_DB_CHANNEL_SIZE                     int
	DI_DB_WHATSAPP                           string
	IPO_SLACK_URL                            string
	STOCKAL_PUBLIC_PEM_PATH                  string
	STOCKAL_SIDECAR_TOPIC                    string
	STOCKAL_APIKEY                           string
	STOCKAL_ACCESSKEY                        string
	STOCKAL_URL                              string
	STOCKALFEED_URL                          string
	STOCKALOAUTHTOKEN_URL                    string
	STOCKAL_PARTNER_SSO_URL                  string
	STOCKAL_JWT_AUD                          string
	STOCKAL_JWT_IIS                          string
	HYPERSYNCLOGIN_URL                       string
	STOCKAL_REDIRECT_URL                     string
	HS_AUTH_KEY_UAT                          string
	HS_PUBLIC_KEY_UAT                        string
	OTPDIGIT                                 int
	OTP_TIMEOUT                              int
	TEAM_CICD                                string
	TEAM_EKS                                 string
	CICD_USER                                string
	CICD_ADMIN                               string
	VERSION                                  string
	RUPEESEED_SALT                           string
	RUPEESEED_IV                             string
	RUPEESEED_PASSTEXT                       string
	RUPEESEED_ENDPOINT                       string
	LOGIN_OTP_DIGITS                         int16
	FORGOTPWD_OTP_DIGITS                     int16
	NETCORE_SMS_FEEDID                       int
	NETCORE_SMS_HOST                         string
	NETCORE_SMS_USERNAME                     string
	NETCORE_SMS_PASSWORD                     string
	NETCORE_EMAIL_API_KEY                    string
	NETCORE_EMAIL_HOST                       string
	NETCORE_EMAIL_CONTENT_TYPE               string
}
